name = "Hexxington"
author = "WhyVex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2301ea94118a2c1de7f1633c67dbebe76aee66c4777d01bbe506e70f13962da"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
