name = "Hexxington"
author = "WhyVex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66f5a9086df1c9a5635ab03cf01a524a880b1eba41f68bb3af78424e7ad5f196"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
