name = "Hexxington"
author = "WhyVex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be569873e118ae5aa3e0523380c0646ec01ce47daf218d7fe36c16b2259cfeba"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
